baseurl: "/"
title: "Statistical Methods in Imaging"
canonifyurls: true
theme: "hugo-conference"
ignoreFiles: [ "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls: true
params:
  # Conference info
  Name: "Statistical Methods in Imaging"
  Description: "Conference description"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Emory University"
  Address: "201 Dowman Dr,"
  City:  "Atlanta"
  State: "GA"
  # Images: ["/img/badge.jpg"]
  GoogleMapsKey: AIzaSyAzseqRz7z7Cxrf6n0iZKcxuY5ffAxFRI0

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - previous
    #- speakers
    #- agenda
    - sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    previous: "Previous Meetings"
    #speakers: "Speakers"
    #agenda: "Agenda"
    sponsors: "Sponsors"
    #partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "More Info Soon!"

  # The entire schedule
 # Agenda:
  #  - name: "Schedule PDF"
 #     link:
#        href: "schedule.pdf"

  # List of Sponsors
  Sponsors:
    - name: "ASA"
      logo: "/img/ASA.png"
      url: "https://www.amstat.org/"
      bio: "Section on Statistics in Imaging"


