baseurl: "/"
title: "Statistical Methods in Imaging"
canonifyurls: true
theme: "hugo-conference"
ignoreFiles: [ "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls: true
params:
  # Conference info
  Name: "Statistical Methods in Imaging"
  Description: "Conference description"
  Date: "June 5-7"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "University of Pennsylvania"
  Address: "422 Curie Blvd,"
  City:  "Philadelphia"
  State: "PA"
  # Images: ["/img/badge.jpg"]
  GoogleMapsKey: AIzaSyAzseqRz7z7Cxrf6n0iZKcxuY5ffAxFRI0

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    #- speakers
    #- agenda
    - sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    #speakers: "Speakers"
    #agenda: "Agenda"
    sponsors: "Sponsors"
    #partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://upenn.irisregistration.com/Form/smi2018"

  # The entire schedule
 # Agenda:
  #  - name: "Schedule PDF"
 #     link:
#        href: "schedule.pdf"

  # List of Sponsors
  Sponsors:
    - name: "ASA"
      logo: "/img/ASA.png"
      url: "https://www.amstat.org/"
      bio: "Section on Statistics in Imaging"
    - name: "CCEB"
      logo: "http://www.cceb.med.upenn.edu/sites/default/files/uploads/cceb_logo.png"
      url: "http://www.cceb.med.upenn.edu/"
      bio: "Center for Clinical Epidemiology and Biostatistics"

