baseurl: "https://example.org/"
title: "Statistical Methods in Imaging"
canonifyurls: true
theme: "hugo-conference"
ignoreFiles: [ "\\.Rmarkdown$", "_files$", "_cache$"]

params:
  # Conference info
  Name: "Statistical Methods in Imaging"
  Description: "Conference description"
  Date: "June 5-7"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "University of Pennsylvania"
  Address: "422 Curie Blvd,"
  City:  "Philadelphia"
  State: "PA"
  # Images: ["/img/badge.jpg"]
  GoogleMapsKey: AIzaSyAzseqRz7z7Cxrf6n0iZKcxuY5ffAxFRI0

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    #- speakers
    #- schedule
    - sponsors
    #- partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    #speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now!"
  #  link: "http://register.example.com"

  # The entire schedule
  Schedule:
    - name: "Schedule PDF"
      link:
        href: "schedule.pdf"

  # List of Sponsors
  Sponsors:
    - name: "ASA"
      logo: "/img/ASA.png"
      url: "https://www.amstat.org/"
      bio: "AMStat imaging section"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"